# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/media" =
    { device = "/media";
      fsType = "tmpfs";
      options = [ "noatime" ];
    };

  fileSystems."/tmp" =
    { device = "/tmp";
      fsType = "tmpfs";
      options = [ "noatime" ];
    };

  boot.initrd.luks.devices."NIXCRYPT".device = "/dev/disk/by-uuid/17033c83-f6db-4034-912f-d84948e0cb8e";
  boot.initrd.luks.devices."NIXCRYPT".bypassWorkqueues = true;
  boot.initrd.luks.devices."NIXCRYPT".allowDiscards = true;

  fileSystems."/" =
    { device = "/dev/mapper/NIXCRYPT";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "compress-force=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/NIXCRYPT";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress-force=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/NIXCRYPT";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "compress-force=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "noatime" ];
    };

  swapDevices = [  { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
