
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.numberwidth = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.cindent = true
vim.opt.smartcase = true
vim.opt.ignorecase = true
vim.opt.fileencoding = "utf-8"
vim.opt.encoding = "utf-8"
vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.opt.writebackup = true
vim.opt.swapfile = false
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.pumheight = 7
vim.opt.backspace = "indent,eol,start"
vim.opt.undofile = true
vim.opt.mouse = ""
vim.opt.mousemoveevent = false
vim.opt.cursorline = true
vim.opt.guicursor = 'n-v-c-sm:hor20,ci-ve:ver25,r-cr-o:block,i:ver25,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor'
vim.opt.title = true
vim.opt.conceallevel = 0
vim.opt.hlsearch = false
vim.opt.showmode = false
vim.opt.laststatus = 2
vim.opt.showtabline = 0
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.termguicolors = true
vim.opt.timeoutlen = 500
vim.opt.updatetime = 300
vim.opt.wrap = true
vim.opt.list = true
vim.opt.splitkeep = "screen"
vim.opt.fillchars = { eob = " ", foldopen = "", foldsep = " ", foldclose = "", lastline = " " }
vim.opt.listchars = "tab:  "
vim.opt.foldenable = false
vim.opt.signcolumn = "yes"
vim.opt.scrolloff = 20
vim.opt.cmdheight = 0
